[package]
name = "kanaya_common"
description = "Shared Kanaya code."
authors = [ "Isabella Lulamoon <kawapure@gmail.com>" ]
repository = "https://github.com/NetworkNeighborhood/kanaya"
version = "1.0.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }