[package]
name = "kanaya_common"
description = "Shared Kanaya code."
authors = [ "Isabella Lulamoon <kawapure@gmail.com>" ]
repository = "https://github.com/NetworkNeighborhood/kanaya"
version = "1.0.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
fluent = { workspace = true }
fluent-fallback = { workspace = true }
futures = "0.3.31"
rustc-hash = "1"
unic-langid = { workspace = true }
